import { Mailbox } from "lucide-react";
import Head from "next/head";
import React from "react";
import { ReceivedRequestRow } from "~/components/candidate/Request";
import { PageHeader } from "~/components/ui";
import CandidateLayout from "~/layouts/candidate-layout";
import { api } from "~/utils/api";

const Received = () => {
  const { data: GigRequests } =
    api.gigRequest.getGigRequestByCandidate.useQuery();
  if (!GigRequests) return null;

  return (
    <>
      <Head>
        <title>RecruJobs/Candidate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CandidateLayout>
        <div className="container">
          <PageHeader title="Received Gig Requests" Icon={Mailbox} />
          <div className="w-full overflow-x-visible">
            <table className="table w-full">
              {/* head */}
              <thead>
                <tr>
                  <th>Recruter Name</th>
                  <th>Gig Title</th>
                  <th>Job Assigned</th>
                  <th>request status</th>
                  <th>
                    <span className="flex items-center justify-center">
                      action
                    </span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {GigRequests.gigRequests.map((request) => (
                  <ReceivedRequestRow key={request.id} request={request} />
                ))}
              </tbody>
              {/* foot */}
              <tfoot>
                <tr>
                  <th>nav</th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th>
                    <span className="flex justify-end px-4">page</span>
                  </th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </CandidateLayout>
    </>
  );
};

export default Received;
