import { Send } from "lucide-react";
import Head from "next/head";
import React from "react";
import SentRequestRow from "~/components/candidate/sent/sent-request-row";
import { PageHeader } from "~/components/ui";
import CandidateLayout from "~/layouts/candidate-layout";
import { api } from "~/utils/api";

const Sent = () => {
  const { data: JobRequests } = api.jobRequest.getRequestByCandidate.useQuery();
  return (
    <>
      <Head>
        <title>RecruJobs/Candidate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CandidateLayout>
        <div className="container">
          <PageHeader title="Sent Request" Icon={Send} />
          <div className="w-full overflow-x-visible">
            <table className="table w-full">
              {/* head */}
              <thead>
                <tr>
                  <th>Recruter Name</th>
                  <th>Your Request on</th>
                  <th>request status</th>
                  <th>
                    <span className="flex items-center justify-center ">
                      action
                    </span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {JobRequests?.jobRequests.map((request) => (
                  <SentRequestRow key={request.id} sentRequest={request} />
                ))}
              </tbody>
              {/* foot */}
              <tfoot>
                <tr>
                  <th>nav</th>
                  <th></th>
                  <th></th>
                  <th>
                    <span className="flex justify-end px-4">page</span>
                  </th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </CandidateLayout>
    </>
  );
};

export default Sent;
