import { FileCog2 } from "lucide-react";
import Head from "next/head";
import { ManageJobCard } from "~/components/recruter/manage-jobs";
import { PageHeader } from "~/components/ui";
import RecruterLayout from "~/layouts/recruter-layout";
import { api } from "~/utils/api";

/**
 * The Recruter manage jobs page.
 */
export default function ManageJobs() {
  const { data: jobs } = api.job.getJobByRecruter.useQuery();
  return (
    <>
      <Head>
        <title>RecruJobs/Recruter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecruterLayout>
        <main>
          <PageHeader title="Manage jobs" Icon={FileCog2} />
          <div className="container py-4">
            <div className="container grid grid-cols-3 gap-16 py-4">
              {jobs?.map((job) => (
                <ManageJobCard key={job.id} job={job} />
              ))}
            </div>
          </div>
        </main>
      </RecruterLayout>
    </>
  );
}
