import { UserCog2 } from "lucide-react";
import Head from "next/head";
import React from "react";
import { ManageGigCard } from "~/components/candidate/manage-gigs";
import { PageHeader } from "~/components/ui";
import CandidateLayout from "~/layouts/candidate-layout";
import { api } from "~/utils/api";

export default function ManageGigs() {
  const { data: gigs } = api.gig.getGigByCondidate.useQuery();
  return (
    <>
      <Head>
        <title>RecruJobs/Candidate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CandidateLayout>
        <main>
          <PageHeader title="Manage jobs" Icon={UserCog2} />
          <div className="container py-4">
            <div className="container grid grid-cols-3 gap-16 py-4">
              {gigs?.map((gig) => (
                <ManageGigCard gig={gig} key={gig.id} />
              ))}
            </div>
          </div>
        </main>
      </CandidateLayout>
    </>
  );
}
