import React from "react";
import { FileCog2 } from "lucide-react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { PageHeader } from "~/components/ui";
import RecruterLayout from "~/layouts/recruter-layout";
import { api } from "~/utils/api";
import { EditJobPost } from "~/components/recruter/manage-jobs";

const EditJob: NextPage = () => {
  // Get the router object to access the query parameters
  const { query } = useRouter();

  const { data: jobPost } = api.job.getJobById.useQuery({
    id: query.id as string,
  });

  if (!jobPost) {
    return null;
  }

  return (
    <>
      <Head>
        <title>RecruJobs/Recruter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecruterLayout>
        <main>
          <PageHeader title="Manage jobs" Icon={FileCog2} />
          <EditJobPost jobPost={jobPost} key={jobPost.id} />
        </main>
      </RecruterLayout>
    </>
  );
};

export default EditJob;
