import { Home } from "lucide-react";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";
import ThemeApplyer from "~/components/ui/theme-applyer";
import MainLayout from "~/layouts/main-layout";

/**
 * The Welcome page.
 */
export default function Welcome() {
  const { data: session } = useSession();
  const { status: sessionStatus } = useSession();
  const router = useRouter();

  if (session?.user.role === "ADMIN" && sessionStatus === "authenticated") {
    return router.push("/admin");
  }

  return (
    <>
      <Head>
        <title>RecruJobs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <main className="relative flex h-screen w-screen items-center justify-center overflow-hidden">
          <div className="container">
            <div className="flex flex-wrap">
              <div className="w-full px-4">
                <div className="dark:bg-dark mx-auto max-w-[500px] rounded-md bg-primary bg-opacity-5 px-6 py-10 sm:p-[60px]">
                  <Link
                    href="/"
                    className="shadow-one mb-11 flex w-full items-center justify-center gap-2 rounded-md bg-info p-3 font-medium text-white hover:bg-opacity-80"
                  >
                    <Home />
                    <span className="font-semibold">Go back to home page</span>
                  </Link>
                  <h3 className="text-body-color mb-3 text-center text-2xl font-bold sm:text-3xl">
                    You can login as:
                  </h3>
                  <div className="flex justify-center">
                    <div className="tabs tabs-boxed gap-4 p-4">
                      <Link href="/recruter" className="btn-primary btn">
                        Recruter
                      </Link>
                      <Link href="/candidate" className="btn-primary btn">
                        Candidate
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <ThemeApplyer />
        </main>
      </MainLayout>
    </>
  );
}
