import { Briefcase } from "lucide-react";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import {
  JobCard,
  JobCardTwo,
  JobDetails,
} from "~/components/candidate/dashboard";
import { PageHeader, Spinner } from "~/components/ui";
import CandidateLayout from "~/layouts/candidate-layout";
import { api } from "~/utils/api";

const JobPost = () => {
  const { query } = useRouter();
  const { data: job } = api.job.getJobById.useQuery({
    id: query.id as string,
  });

  const jobList = api.job.getjobs.useQuery();

  if (!job || !jobList) {
    return <Spinner />;
  }

  return (
    <>
      <Head>
        <title>RecruJobs/Candidate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CandidateLayout>
        <main>
          <PageHeader title="Job post" Icon={Briefcase} />
          <div className="flex">
            <div className="container rounded-box w-[60%] space-y-4 bg-base-300 p-8">
              <p className="text:sm italic text-slate-500">
                NOTE: Take your time to explore the details of each position and
                apply for the ones that resonate with your skills and ambitions.
              </p>
              <JobCardTwo job={job} key={job.id} />
              {jobList.data?.map(
                (job) =>
                  job.id !== query.id && <JobCard job={job} key={job.id} />
              )}
            </div>
            <div className="container w-[40%]">
              <JobDetails job={job} />
            </div>
          </div>
        </main>
      </CandidateLayout>
    </>
  );
};

export default JobPost;
