import Head from "next/head";
import CandidateLayout from "~/layouts/candidate-layout";
import { api } from "~/utils/api";

/**
 * The Profile page.
 */
export default function Profile() {
  const { data: candidate } = api.candidate.getUserCandidate.useQuery();

  return (
    <>
      <Head>
        <title>{candidate?.fullName}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CandidateLayout>
        <h1>Profile</h1>
      </CandidateLayout>
    </>
  );
}
