import { UserCircle2 } from "lucide-react";
import Head from "next/head";
import { PageHeader } from "~/components/ui";
import CandidateLayout from "~/layouts/candidate-layout";
import { api } from "~/utils/api";

// Import styles
import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";
import { Viewer, Worker } from "@react-pdf-viewer/core";

const Edit = () => {
  const { data: candidate } = api.candidate.getUserCandidate.useQuery();
  const resume = candidate?.resume as string;

  return (
    <>
      <Head>
        <title>{candidate?.fullName}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CandidateLayout>
        <div className="container">
          <PageHeader title="Profile Page" Icon={UserCircle2} />
        </div>
        <div className="container">
          <div className="flex w-full">
            <div className="container card rounded-box grid flex-grow border border-primary bg-base-300">
              <div className="container py-8">
                {/* Condidate info */}
                <div className="divider"></div>
                <form className="text-center">
                  {/* Section title */}
                  <h1 className="rounded-lg bg-primary py-2 text-xl font-bold text-slate-100">
                    Condidate Info
                  </h1>
                  <div className="divider"></div>
                  <div className="space-y-2 py-2">
                    {/* Full name */}
                    <div className="flex items-center justify-between text-lg">
                      <span className="font-semibold">Full Name: </span>
                      <input
                        type="text"
                        placeholder={candidate?.fullName}
                        className="input-bordered input-primary input max-w-xs"
                      />
                    </div>
                    {/* Phone */}
                    <div className="flex items-center justify-between text-lg">
                      <span className="font-semibold">Phone: </span>
                      <input
                        type="text"
                        placeholder={candidate?.phone}
                        className="input-bordered input-primary input max-w-xs"
                      />
                    </div>
                    {/* E-mail */}
                    <div className="flex items-center justify-between text-lg">
                      <span className="font-semibold">E-mail: </span>
                      <input
                        type="text"
                        placeholder={candidate?.email}
                        className="input-bordered input-primary input max-w-xs"
                      />
                    </div>
                    {/* City */}
                    <div className="flex items-center justify-between text-lg">
                      <span className="font-semibold">City: </span>
                      <input
                        type="text"
                        placeholder={candidate?.city}
                        className="input-bordered input-primary input max-w-xs"
                      />
                    </div>
                    {/* Address */}
                    <div className="flex items-center justify-between text-lg">
                      <span className="font-semibold">Address: </span>
                      <input
                        type="text"
                        placeholder={candidate?.address}
                        className="input-bordered input-primary input max-w-xs"
                      />
                    </div>
                    {/* Postal Code */}
                    <div className="flex items-center justify-between text-lg">
                      <span className="font-semibold">Postal Code: </span>
                      <input
                        type="text"
                        placeholder={candidate?.postalCode}
                        className="input-bordered input-primary input max-w-xs"
                      />
                    </div>
                  </div>
                  <div className="divider"></div>
                  <div>
                    <button className="btn-primary btn-sm btn">submit</button>
                  </div>
                </form>
              </div>
            </div>
            <div className="divider divider-horizontal"></div>
            <div className="container card rounded-box grid flex-grow border border-primary bg-base-300 py-7">
              <div className="divider"></div>
              <h1 className="flex justify-center rounded-lg bg-primary py-2 text-xl font-bold text-slate-100">
                Resume
              </h1>
              <div className="divider"></div>
              <div className="flex w-full justify-center">
                <div className="flex w-[300px] justify-center">
                  <Worker workerUrl="https://unpkg.com/pdfjs-dist@3.6.172/build/pdf.worker.js">
                    <Viewer fileUrl={resume} />
                  </Worker>
                </div>
              </div>
              <div className="divider"></div>
              <form className="">
                <label htmlFor="pdf" className="pb-2 font-semibold">
                  Select your resume:
                </label>
                <input
                  className="file-input-bordered file-input-primary file-input w-full"
                  id="pdf"
                  type="file"
                />
                <div className="divider"></div>
                <div className="flex justify-center">
                  <button className="btn-primary btn-sm btn">submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div className="container">
          <div className="divider"></div>
          <div className="container card rounded-box grid flex-grow border border-primary bg-base-300 py-7">
            <div className="divider"></div>
            <h1 className="flex justify-center rounded-lg bg-primary py-2 text-xl font-bold text-slate-100">
              Socials
            </h1>
            <div className="divider"></div>
            <form className="space-y-2 py-2">
              {/* LinkedIn */}
              <div className="flex items-center justify-between gap-5 text-lg">
                <span className="font-semibold">LinkedIn: </span>
                {(candidate?.linkedIn && (
                  <input
                    type="text"
                    placeholder={candidate?.linkedIn}
                    className="input-bordered input-primary input w-full"
                  />
                )) || (
                  <input
                    type="text"
                    placeholder="LinkedIn"
                    className="input-bordered input-primary input w-full"
                  />
                )}
              </div>
              {/* Twitter */}
              <div className="flex items-center justify-between gap-5 text-lg">
                <span className="font-semibold">Twitter: </span>
                {(candidate?.twitter && (
                  <input
                    type="text"
                    placeholder={candidate?.twitter}
                    className="input-bordered input-primary input w-full"
                  />
                )) || (
                  <input
                    type="text"
                    placeholder="Twitter"
                    className="input-bordered input-primary input w-full"
                  />
                )}
              </div>
              {/* Facebook */}
              <div className="flex items-center justify-between gap-5 text-lg">
                <span className="font-semibold">Facebook: </span>
                {(candidate?.facebook && (
                  <input
                    type="text"
                    placeholder={candidate?.facebook}
                    className="input-bordered input-primary input w-full"
                  />
                )) || (
                  <input
                    type="text"
                    placeholder="Facebook"
                    className="input-bordered input-primary input w-full"
                  />
                )}
              </div>
              {/* Instagram */}
              <div className="flex items-center justify-between gap-5 text-lg">
                <span className="font-semibold">Instagram: </span>
                {(candidate?.instagram && (
                  <input
                    type="text"
                    placeholder={candidate?.instagram}
                    className="input-bordered input-primary input w-full"
                  />
                )) || (
                  <input
                    type="text"
                    placeholder="Instagram"
                    className="input-bordered input-primary input w-full"
                  />
                )}
              </div>
              {/* Github */}
              <div className="flex items-center justify-between gap-5 text-lg">
                <span className="font-semibold">Github: </span>
                {(candidate?.github && (
                  <input
                    type="text"
                    placeholder={candidate?.github}
                    className="input-bordered input-primary input w-full"
                  />
                )) || (
                  <input
                    type="text"
                    placeholder="Github"
                    className="input-bordered input-primary input w-full"
                  />
                )}
              </div>
              {/* Web Site */}
              <div className="flex items-center justify-between gap-5 text-lg">
                <span className="font-semibold">Web Site: </span>
                {(candidate?.website && (
                  <input
                    type="text"
                    placeholder={candidate?.website}
                    className="input-bordered input-primary input w-full"
                  />
                )) || (
                  <input
                    type="text"
                    placeholder="Web Site"
                    className="input-bordered input-primary input w-full"
                  />
                )}
              </div>
              <div className="divider"></div>
              <div className="flex justify-center">
                <button className="btn-primary btn-sm btn">submit</button>
              </div>
            </form>
          </div>
        </div>
      </CandidateLayout>
    </>
  );
};

export default Edit;
