import { UserCog2 } from "lucide-react";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { EditGigPost } from "~/components/candidate/manage-gigs";
import { PageHeader } from "~/components/ui";
import CandidateLayout from "~/layouts/candidate-layout";
import { api } from "~/utils/api";

const EditGig: NextPage = () => {
  // Get the router object to access the query parameters
  const { query } = useRouter();

  const { data: gigPost } = api.gig.getGigById.useQuery({
    id: query.id as string,
  });

  if (!gigPost) {
    return null;
  }

  return (
    <>
      <Head>
        <title>RecruJobs/Candidate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CandidateLayout>
        <main>
          <PageHeader title="Manage jobs" Icon={UserCog2} />
          <EditGigPost gigPost={gigPost} key={gigPost.id} />
        </main>
      </CandidateLayout>
    </>
  );
};

export default EditGig;
