import { UserCircle2 } from "lucide-react";
import Head from "next/head";
import {
  EditRecruiterInfo,
  EditRecruiterSocials,
} from "~/components/recruter/profile";
import { PageHeader } from "~/components/ui";
import RecruterLayout from "~/layouts/recruter-layout";
import { api } from "~/utils/api";

export default function Edit() {
  const { data: recruter } = api.recruter.getUserRecruter.useQuery();

  return (
    <>
      <Head>
        <title>{recruter?.fullName}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecruterLayout>
        <div className="container">
          <PageHeader title="Edit Profile Page" Icon={UserCircle2} />
        </div>
        <div className="container">
          <div className="flex w-full">
            <div className="container card rounded-box grid flex-grow border border-primary bg-base-300">
              <div className="container py-8">
                <div className="divider"></div>
                {/* Recruiter info */}
                <EditRecruiterInfo />
              </div>
            </div>
            <div className="divider divider-horizontal"></div>
            {/* Resume */}
            <div className="container card rounded-box grid flex-grow border border-primary bg-base-300">
              <div className="container py-8">
                <div className="divider"></div>
                {/* Recruiter info */}
                <EditRecruiterSocials />
              </div>
            </div>
          </div>
        </div>
      </RecruterLayout>
    </>
  );
}
