import Head from "next/head";
import CondidateLayout from "~/layouts/condidate-layout";

/**
 * The Condidate page.
 */
export default function Condidate() {
  return (
    <>
      <Head>
        <title>RecruJobs/Condidate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CondidateLayout>
        <main>Condidate Page</main>
      </CondidateLayout>
    </>
  );
}
