import { Contact } from "lucide-react";
import Head from "next/head";
import { ContactRow } from "~/components/admin";
import { PageHeader } from "~/components/ui";
import AdminLayout from "~/layouts/admin-layout";
import { api } from "~/utils/api";

const ContactPage = () => {
  const { data: contacts } = api.contact.getContacts.useQuery();

  return (
    <>
      <Head>
        <title>RecruJobs/Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="container">
          <PageHeader title="Contact" Icon={Contact} />
          <div className="container">
            <div className="w-full overflow-x-visible">
              <table className="table w-full">
                {/* head */}
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Subject</th>
                    <th>Message</th>
                    <th>
                      <span className="flex justify-center">action</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {contacts?.map((contact) => (
                    <ContactRow key={contact.id} contact={contact} />
                  ))}
                </tbody>
                {/* foot */}
                <tfoot>
                  <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default ContactPage;
