import { LayoutDashboard } from "lucide-react";
import Head from "next/head";
import { useState } from "react";
import { UserRow } from "~/components/admin";
import { PageHeader } from "~/components/ui";
import AdminLayout from "~/layouts/admin-layout";
import { api } from "~/utils/api";

const Admin = () => {
  const [searchValue, setSearchValue] = useState<string>("");

  const { data: user } = api.userAdmin.getUsers.useQuery({
    searchValue: searchValue,
  });
  return (
    <>
      <Head>
        <title>RecruJobs/Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="container">
          <PageHeader title="Dashboard" Icon={LayoutDashboard}>
            <div className="input-group w-full ">
              <input
                onChange={(e) => setSearchValue(e.target.value)}
                value={searchValue}
                type="search"
                placeholder="Search…"
                className="input-bordered input w-full border-r-0 border-neutral-content bg-transparent focus:outline-none"
              />
              <button className="btn-square btn border-l-0 border-neutral-content bg-transparent hover:border-neutral-content hover:bg-transparent">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                  />
                </svg>
              </button>
            </div>
          </PageHeader>
          <div className="container">
            <div className="w-full overflow-x-visible">
              <table className="table w-full">
                {/* head */}
                <thead>
                  <tr>
                    <th>User Name</th>
                    <th>candidate profile</th>
                    <th>recruter profile</th>
                    <th>
                      <span className="flex justify-center px-4">action</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {user?.map((user) => (
                    <UserRow key={user.id} user={user} />
                  ))}
                </tbody>
                {/* foot */}
                <tfoot>
                  <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default Admin;
