import Head from "next/head";
import AdminLayout from "~/layouts/admin-layout";

const Admin = () => {
  return (
    <>
      <Head>
        <title>RecruJobs/Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>hello</AdminLayout>
    </>
  );
};

export default Admin;
