import { FileCog2 } from "lucide-react";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useInView } from "react-intersection-observer";
import { ManageJobCard } from "~/components/admin";
import { PageHeader } from "~/components/ui";
import AdminLayout from "~/layouts/admin-layout";
import { api } from "~/utils/api";

const ManageJobs = () => {
  const [searchValue, setSearchValue] = useState<string>("");

  // jobs query
  const {
    data: jobs,
    fetchNextPage,
    hasNextPage,
    isFetching,
  } = api.jobAdmin.getjobs.useInfiniteQuery(
    {
      limit: 6,
      searchValue,
    },
    { getNextPageParam: (lastPage) => lastPage.nextCursor }
  );

  const { ref, inView } = useInView({ threshold: 0 });

  useEffect(() => {
    if (inView && !isFetching && hasNextPage) {
      void fetchNextPage();
    }
  }, [inView, isFetching, hasNextPage, fetchNextPage]);

  return (
    <>
      <Head>
        <title>RecruJobs/Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="container">
          <PageHeader title="Manage jobs" Icon={FileCog2}>
            <div className="input-group w-full ">
              <input
                onChange={(e) => setSearchValue(e.target.value)}
                value={searchValue}
                type="search"
                placeholder="Search…"
                className="input-bordered input w-full border-r-0 border-neutral-content bg-transparent focus:outline-none"
              />
              <button className="btn-square btn border-l-0 border-neutral-content bg-transparent hover:border-neutral-content hover:bg-transparent">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                  />
                </svg>
              </button>
            </div>
          </PageHeader>
          <div className="container py-4">
            <div className="container grid grid-cols-3 gap-16 py-4">
              {jobs?.pages
                .flatMap((page) => page.jobs)
                .map((job) => (
                  <ManageJobCard key={job.id} job={job} />
                ))}
              <div ref={ref}></div>
            </div>
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default ManageJobs;
