import { AlertOctagonIcon } from "lucide-react";
import Head from "next/head";
import React from "react";
import { ReportRow } from "~/components/admin";
import { PageHeader } from "~/components/ui";
import AdminLayout from "~/layouts/admin-layout";
import { api } from "~/utils/api";

const ReportsPage = () => {
  const { data: reports } = api.report.getReports.useQuery();

  return (
    <>
      <Head>
        <title>RecruJobs/Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="container">
          <PageHeader title="Reports" Icon={AlertOctagonIcon} />
          <div className="container">
            <div className="w-full overflow-x-visible">
              <table className="table w-full">
                {/* head */}
                <thead>
                  <tr>
                    <th>Reported By</th>
                    <th>Reported</th>
                    <th>Reason</th>
                    <th>
                      <span className="flex justify-center">action</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {reports?.reports.map((report) => (
                    <ReportRow key={report.id} report={report} />
                  ))}
                </tbody>
                {/* foot */}
                <tfoot>
                  <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default ReportsPage;
