import Head from "next/head";
import { useState } from "react";
import {
  RecruterDone,
  RecruterContact,
  RecruterInfo,
  RecruterSocials,
  RecruterType,
} from "~/components/recruter/become-a-recruter";
import FormSteps from "~/components/recruter/become-a-recruter/form-steps";
import { ThemeApplyer } from "~/components/ui";
import { useForm } from "react-hook-form";
import {
  recruterTypeSchema,
  type RecruterTypeType,
} from "~/validation/recruter/recruterType";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  type RecruterNonOrgType,
  type RecruterOrgType,
  recruterNonOrgSchema,
  recruterOrgSchema,
} from "~/validation/recruter/recruterInfo";

/**
 * The Become a recruter page.
 */
export default function BecomeARecruter() {
  const [currentStep, setCurrentStep] = useState<number>(1);

  /**
   * Recruter type
   */
  const recruterTypeFormMethods = useForm<RecruterTypeType>({
    resolver: zodResolver(recruterTypeSchema),
  });
  const [recruterTypeData, setRecruterTypeData] = useState<RecruterTypeType>();

  /**
   * Recruter info
   */
  const recruterOrgFormMethods = useForm<RecruterOrgType>({
    resolver: zodResolver(recruterOrgSchema),
  });
  const [recruterOrgData, setRecruterOrgData] = useState<RecruterOrgType>();
  const recruterNonOrgFormMethods = useForm<RecruterNonOrgType>({
    resolver: zodResolver(recruterNonOrgSchema),
  });
  const [recruterNonOrgData, setRecruterNonOrgData] =
    useState<RecruterNonOrgType>();

  return (
    <>
      <Head>
        <title>RecruJobs/Welcome</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex h-screen w-screen items-center justify-center overflow-hidden ">
        <div className="space-y-8">
          <h1 className="text-center text-4xl font-bold text-primary">
            Become a recruter
          </h1>
          <FormSteps step={currentStep} />
          <div className="rounded-lg bg-primary bg-opacity-5 p-10">
            {/* Step 1: Recruter Type */}
            {currentStep === 1 && (
              <RecruterType
                methods={recruterTypeFormMethods}
                submitData={(data: RecruterTypeType) => {
                  setRecruterTypeData(data);
                  setCurrentStep((step) => step + 1);
                }}
              />
            )}
            {/* Step 2: Recruter Info */}
            {currentStep === 2 && (
              <RecruterInfo
                isOrganization={
                  recruterTypeData?.isOrganization === "Organization"
                    ? true
                    : false
                }
                orgMethods={recruterOrgFormMethods}
                nonOrgMethods={recruterNonOrgFormMethods}
                goPreviousStep={() => setCurrentStep((step) => step - 1)}
                submitOrgData={(data: RecruterOrgType) => {
                  setRecruterOrgData(data);
                  setCurrentStep((step) => step + 1);
                }}
                submitNonOrgData={(data: RecruterNonOrgType) => {
                  setRecruterNonOrgData(data);
                  setCurrentStep((step) => step + 1);
                }}
              />
            )}
            {/* Step 3: Recruter Contact */}
            {currentStep === 3 && <RecruterContact />}
            {/* Step 4: Recruter Socials */}
            {currentStep === 4 && <RecruterSocials />}
            {/* Step 5: Done Submit data */}
            {currentStep === 5 && <RecruterDone />}
          </div>
        </div>
        <ThemeApplyer />
      </main>
    </>
  );
}
