import { LayoutDashboard } from "lucide-react";
import Head from "next/head";
import { PageHeader } from "~/components/ui";
import RecruterLayout from "~/layouts/recruter-layout";

/**
 * The Recruter page.
 */
export default function Recruter() {
  return (
    <>
      <Head>
        <title>RecruJobs/Recruter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecruterLayout>
        <div className="container">
          <PageHeader title="Dashboard" Icon={LayoutDashboard} />
        </div>
      </RecruterLayout>
    </>
  );
}
