import Head from "next/head";
import { api } from "~/utils/api";
import RecruterLayout from "~/layouts/recruter-layout";
import { PageHeader } from "~/components/ui";
import { ClipboardSignature } from "lucide-react";

/**
 *  PostAJob Page
 */
const PostAJob = () => {
  const { data: recruter } = api.recruter.getUserRecruter.useQuery();

  return (
    <>
      <Head>
        <title>{recruter?.fullName}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecruterLayout>
        <div className="container">
          {/* Page Header */}
          <PageHeader title="Post A Job" Icon={ClipboardSignature} />
          <div className="container">
            <div className="flex w-full">
              <div className="container card rounded-box grid flex-grow border border-primary bg-base-300">
                <div className="container py-8">
                  {/* Page noation */}
                  <div className="">
                    <p className="text:sm italic text-slate-500">
                      NOTE: Lorem ipsum dolor sit amet consectetur adipisicing
                      elit. Alias eaque blanditiis velit iste natus tenetur id
                      nisi neque omnis consequuntur ex explicabo voluptatibus a
                      culpa, ipsum eius aspernatur nulla nostrum?
                    </p>
                  </div>
                  <div className="divider"></div>
                  {/* FORM */}
                  <form className="">
                    <div className="container grid grid-cols-2 py-2">
                      {/* Form Col 1 */}
                      <div className="container space-y-4">
                        {/* Job Title */}
                        <div className="container flex flex-col gap-1.5">
                          <label className="pl-1 font-bold" htmlFor="jobTitle">
                            Job Title :{" "}
                          </label>
                          <input
                            id="jobTitle"
                            type="text"
                            placeholder="Type here"
                            className="input-bordered input-primary input w-full"
                          />
                        </div>
                        {/* Job Type */}
                        <div className="container flex flex-col gap-1.5">
                          <label className="pl-1 font-bold" htmlFor="jobType">
                            Job Type :{" "}
                          </label>
                          <select
                            id="jobType"
                            className="select-primary select w-full"
                          >
                            <option>Full Time</option>
                            <option>Half Time</option>
                            <option>Freelance</option>
                            <option>Temporary</option>
                          </select>
                        </div>
                        {/* Hours of Work */}
                        <div className="container flex flex-col gap-1.5">
                          <label
                            className="pl-1 font-bold"
                            htmlFor="hoursOfWork"
                          >
                            Hours of work :{" "}
                          </label>
                          <input
                            id="hoursOfWork"
                            type="text"
                            placeholder="Type here"
                            className="input-bordered input-primary input w-full"
                          />
                        </div>
                      </div>
                      {/* Form Col 2 */}
                      {/* Job Location */}
                      <div className="container space-y-4">
                        <div className="container flex flex-col gap-1.5">
                          <label
                            className="pl-1 font-bold"
                            htmlFor="jobLocation"
                          >
                            Job Location :{" "}
                          </label>
                          <input
                            id="jobLocation"
                            type="text"
                            placeholder="Type here"
                            className="input-bordered input-primary input w-full"
                          />
                        </div>
                        {/* Years Of Experience */}
                        <div className="container flex flex-col gap-1.5">
                          <label
                            className="pl-1 font-bold"
                            htmlFor="yearsOfExperience"
                          >
                            Years Of Experience :{" "}
                          </label>
                          <select
                            id="yearsOfExperience"
                            className="select-primary select w-full"
                          >
                            <option>Less then one year</option>
                            <option>1 year</option>
                            <option>2 years</option>
                            <option>3 years</option>
                            <option>4 years</option>
                            <option>5 years plus</option>
                          </select>
                        </div>
                        {/* Salary */}
                        <div className="container flex flex-col gap-1.5">
                          <label className="pl-1 font-bold" htmlFor="salary">
                            Salary :{" "}
                          </label>
                          <input
                            id="salary"
                            type="text"
                            placeholder="Type here"
                            className="input-bordered input-primary input w-full"
                          />
                        </div>
                      </div>
                    </div>
                    {/* Job Description */}
                    <div className="container py-4">
                      <div className="flex flex-col gap-1.5 px-12">
                        <label
                          className="pl-1 font-bold"
                          htmlFor="jobDescription"
                        >
                          Job Description:{" "}
                        </label>
                        <textarea
                          id="jobDescription"
                          className="textarea-primary textarea h-36"
                          placeholder="Bio"
                        ></textarea>
                      </div>
                    </div>
                    <div className="divider"></div>
                    {/* Submit btn */}
                    <div className="flex items-center justify-center">
                      <button className="btn-primary btn">Button</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </RecruterLayout>
    </>
  );
};

export default PostAJob;
