import { Send } from "lucide-react";
import Head from "next/head";
import React from "react";
import { SentRequestRow } from "~/components/recruter/Request";
import { PageHeader } from "~/components/ui";
import RecruterLayout from "~/layouts/recruter-layout";
import { api } from "~/utils/api";

const Sent = () => {
  const { data: gigRequests } = api.gigRequest.getRequestByRecruter.useQuery();

  return (
    <>
      <Head>
        <title>Recruter/Sent</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecruterLayout>
        <div className="container">
          <PageHeader title="Sent Request" Icon={Send} />
          <div className="w-full overflow-x-visible">
            <table className="table w-full">
              {/* head */}
              <thead>
                <tr>
                  <th>Recruter Name</th>
                  <th>Gig Title</th>
                  <th>Job Assigned</th>
                  <th>request status</th>
                  <th>
                    <span className="flex items-center justify-center ">
                      action
                    </span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {gigRequests?.gigRequests.map((request) => (
                  <SentRequestRow
                    key={request.id}
                    id={request.id}
                    gig={request.gig}
                    job={request.job}
                    status={request.status}
                  />
                ))}
              </tbody>
              {/* foot */}
              <tfoot>
                <tr>
                  <th>nav</th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th>
                    <span className="flex justify-end px-4">page</span>
                  </th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </RecruterLayout>
    </>
  );
};

export default Sent;
